name: fgs_utils
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  provider: ^6.1.1
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
